CREATE OR REPLACE WAREHOUSE LOANS_WH
WITH
WAREHOUSE_SIZE = XSMALL
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT =3
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE
COMMENT = "Loans Warehouse"

ALTER WAREHOUSE LOANS_WH RESUME

ALTER WAREHOUSE LOANS_WH SUSPEND

ALTER WAREHOUSE LOANS_WH SET WAREHOUSE_SIZE = 'XSMALL'

DROP WAREHOUSE LOANS_WH