CREATE OR REPLACE WAREHOUSE SALES_WH
WITH
WAREHOUSE_SIZE = XSMALL
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT =3
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE
COMMENT = "Sales Warehouse"

ALTER WAREHOUSE SALES_WH RESUME

ALTER WAREHOUSE SALES_WH SUSPEND

ALTER WAREHOUSE SALES_WH SET WAREHOUSE_SIZE = 'XSMALL'

DROP WAREHOUSE SALES_WH


